## Metadata for IBM Node.js sample configuration
## This metadata is used to augment the values.yaml file to drive the ICP UI for configuration of the Helm chart installation

## Image configuration metadata
image:
  __metadata:
    label: "Docker image configuration"
  repository:
    __metadata:
      name: "Repository"
      label: "Docker Repository"
      description: "Docker registry to pull image from."
      type: "string"
      immutable: "false"
      required: true
  pullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Docker image pull policy"
      description: "Always, Never, or IfNotPresent. Defaults to IfNotPresent"
      type: "string"
      immutable: "false"
      required: true
      options:
      - label: "IfNotPresent"
        value: "IfNotPresent"
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"

## Service configuration metadata
service:
  __metadata:
    label: "Service configuration"
  name: 
    __metadata:
      name: "Name"
      label: "Service Name"
      description: "This is the Service Name"
      type: "string"
      immutable: "false"
      required: true
      validation: "^[a-zA-Z]([-a-zA-Z0-9])+$"
  type: 
    __metadata:
      name: "Type"
      label: "Service Type"
      description: "This is the Service Type"
      type: "string"
      immutable: "false"
      required: true
      options:
        - label: "Cluster IP"
          value: "ClusterIP"
        - label: "Node Port"
          value: "NodePort"
